services:
  
  monorepo:
    build:
      context: .
    init: true
    command: ./dev.sh
    ports:
      - "3000:3000"
      - "3001:3001"
    develop:
      watch:
        - action: sync
          path: ./
          target: /monorepo
