services:
  
  monorepo:
    build:
      context: .
    init: true
    command: ./node_modules/.bin/concurrently "npm run dev --workspace=server" "npm run dev --workspace=greet-service"
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/monorepo
      - not-used:/monorepo/node_modules

volumes:
  not-used:
    
